// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t *ui_Screen3;
extern lv_obj_t *ui_Bar1;
extern lv_obj_t *ui_Arc2;
extern lv_obj_t *ui_Panel6;
extern lv_obj_t *ui_Label20;
extern void ui_event_Button5( lv_event_t * e);
extern lv_obj_t *ui_Button5;
extern lv_obj_t *ui_Container17;
extern lv_obj_t *ui_Container12;
extern lv_obj_t *ui_Container10;
extern lv_obj_t *ui_Label16;
extern lv_obj_t *ui_Label22;
extern lv_obj_t *ui_Container11;
extern lv_obj_t *ui_Slider1;
extern lv_obj_t *ui_Switch1;
extern lv_obj_t *ui_Container13;
extern lv_obj_t *ui_batteryBar2;
extern lv_obj_t *ui_batteryPercent2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

