// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_Panel7;
extern lv_obj_t *ui_Arc6;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_timer_arc1;
extern void ui_event_Button3( lv_event_t * e);
extern lv_obj_t *ui_Button3;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_Container3;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Container6;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_Container7;
extern lv_obj_t *ui_Label15;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Container8;
extern lv_obj_t *ui_Label17;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_Container9;
extern lv_obj_t *ui_Label18;
extern lv_obj_t *ui_Label19;
extern lv_obj_t *ui_Image9;
extern void ui_event_Button4( lv_event_t * e);
extern lv_obj_t *ui_Button4;
extern lv_obj_t *ui_Panel3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

