// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_textBackground;
extern lv_obj_t *ui_eventOverlay;
extern lv_obj_t *ui_divider;
extern lv_obj_t *ui_eventLabel;
extern lv_obj_t *ui_timer_arc;
extern void ui_event_pageChangeButton( lv_event_t * e);
extern lv_obj_t *ui_pageChangeButton;
extern lv_obj_t *ui_timeLabel;
extern lv_obj_t *ui_Container14;
extern lv_obj_t *ui_batteryBar3;
extern lv_obj_t *ui_batteryPercent3;
extern lv_obj_t *ui_Label2;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Arc3;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

