// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "schedule_manager.h"
#include "display_helpers.h"
#include <time.h>

lv_obj_t *uic_Arc3;
lv_obj_t *ui_Screen1 = NULL;
lv_obj_t *ui_Image1 = NULL;
lv_obj_t *ui_textBackground = NULL;
lv_obj_t *ui_eventOverlay = NULL;
lv_obj_t *ui_timer_arc = NULL;
lv_obj_t *ui_Image5 = NULL;
lv_obj_t *ui_pageChangeButton = NULL;
lv_obj_t *ui_Container5 = NULL;
lv_obj_t *ui_timeLabel = NULL;
lv_obj_t *ui_eventLabel = NULL;
lv_obj_t *ui_currentTimeLabel = NULL;
lv_obj_t *ui_Container14 = NULL;
lv_obj_t *ui_batteryBar3 = NULL;
lv_obj_t *ui_batteryPercent3 = NULL;

// event funtions
void ui_event_pageChangeButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_Screen2_screen_init);
}
}

void ui_event_timer_arc(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * arc = lv_event_get_target(e);
    
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        // The arc value has changed, you can add custom logic here if needed
        int value = lv_arc_get_value(arc);
        // For example, update a label or perform some action based on the value
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_image_create(ui_Screen1);
// lv_image_set_src(ui_Image1, &ui_img_backpacks_png);  // Image moved to SD card
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_Image1,125);

ui_textBackground = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_textBackground, 420);
lv_obj_set_height( ui_textBackground, 420);
lv_obj_set_x( ui_textBackground, 0 );
lv_obj_set_y( ui_textBackground, 32 );
lv_obj_set_align( ui_textBackground, LV_ALIGN_CENTER );
lv_arc_set_value(ui_textBackground, 0);
lv_arc_set_bg_angles(ui_textBackground,0,180);
lv_obj_set_style_arc_color(ui_textBackground, lv_color_hex(0x304B59), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_textBackground, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_textBackground, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_textBackground, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_textBackground, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_textBackground, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_eventOverlay = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_eventOverlay, 480);
lv_obj_set_height( ui_eventOverlay, 480);
lv_obj_set_align( ui_eventOverlay, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_eventOverlay, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_eventOverlay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_eventOverlay, 70, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_eventOverlay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_eventOverlay, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_timer_arc = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_timer_arc, 480);
lv_obj_set_height( ui_timer_arc, 480);
lv_obj_set_align( ui_timer_arc, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_timer_arc, LV_OBJ_FLAG_CLICKABLE );    /// Make it touchable
lv_arc_set_value(ui_timer_arc, 90);
lv_arc_set_bg_angles(ui_timer_arc,0,360);
lv_arc_set_mode(ui_timer_arc, LV_ARC_MODE_REVERSE);
lv_arc_set_rotation(ui_timer_arc,270);
lv_obj_set_style_arc_color(ui_timer_arc, lv_color_hex(0x304B59), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_timer_arc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_timer_arc, 30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_object_set_themeable_style_property(ui_timer_arc, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR, _ui_theme_color_Baby_Blue);
ui_object_set_themeable_style_property(ui_timer_arc, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_ARC_OPA, _ui_theme_alpha_Baby_Blue);
lv_obj_set_style_arc_width(ui_timer_arc, 30, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_timer_arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_timer_arc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Image5 = lv_image_create(ui_Screen1);
// lv_image_set_src(ui_Image5, &ui_img_rightarrow2_png);  // Image moved to SD card
lv_obj_set_width( ui_Image5, LV_SIZE_CONTENT);  /// 20
lv_obj_set_height( ui_Image5, LV_SIZE_CONTENT);   /// 200
lv_obj_set_x( ui_Image5, 181 );
lv_obj_set_y( ui_Image5, 0 );
lv_obj_set_align( ui_Image5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image5, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Image5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_Image5,100);

ui_pageChangeButton = lv_button_create(ui_Screen1);
lv_obj_set_width( ui_pageChangeButton, 58);
lv_obj_set_height( ui_pageChangeButton, 81);
lv_obj_set_x( ui_pageChangeButton, 173 );
lv_obj_set_y( ui_pageChangeButton, 1 );
lv_obj_set_align( ui_pageChangeButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_pageChangeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_pageChangeButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_pageChangeButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_pageChangeButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_pageChangeButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_pageChangeButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container5 = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Container5);
lv_obj_set_width( ui_Container5, 324);
lv_obj_set_height( ui_Container5, 204);
lv_obj_set_x( ui_Container5, 0 );
lv_obj_set_y( ui_Container5, -9 );
lv_obj_set_align( ui_Container5, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container5,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_timeLabel = lv_label_create(ui_Container5);
lv_obj_set_width( ui_timeLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_timeLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_timeLabel, 0 );
lv_obj_set_y( ui_timeLabel, -47 );
lv_obj_set_align( ui_timeLabel, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_timeLabel,LV_LABEL_LONG_SCROLL);
lv_label_set_text(ui_timeLabel,"5:48");
lv_obj_set_style_text_color(ui_timeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_timeLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_timeLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_timeLabel, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_eventLabel = lv_label_create(ui_Container5);
lv_obj_set_width( ui_eventLabel, lv_pct(98));
lv_obj_set_height( ui_eventLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_eventLabel, 0 );
lv_obj_set_y( ui_eventLabel, -3 );
lv_obj_set_align( ui_eventLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_eventLabel,"School");
lv_obj_remove_flag( ui_eventLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_eventLabel, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_eventLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_eventLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_eventLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_eventLabel, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container14 = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Container14);
lv_obj_set_width( ui_Container14, 104);
lv_obj_set_height( ui_Container14, 45);
lv_obj_set_x( ui_Container14, 0 );
lv_obj_set_y( ui_Container14, -179 );
lv_obj_set_align( ui_Container14, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container14,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container14, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_batteryBar3 = lv_bar_create(ui_Container14);
lv_bar_set_value(ui_batteryBar3,75,LV_ANIM_OFF);
lv_bar_set_start_value(ui_batteryBar3, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_batteryBar3, 50);
lv_obj_set_height( ui_batteryBar3, 20);
lv_obj_set_x( ui_batteryBar3, 78 );
lv_obj_set_y( ui_batteryBar3, 63 );
lv_obj_set_align( ui_batteryBar3, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_batteryBar3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_batteryBar3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_batteryBar3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_batteryBar3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_batteryBar3, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_batteryBar3, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_batteryBar3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_batteryBar3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_batteryBar3, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_batteryBar3, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_batteryBar3, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_batteryBar3, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_batteryBar3, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_batteryBar3, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_batteryBar3,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_batteryBar3, lv_obj_get_style_pad_right(ui_batteryBar3,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_batteryPercent3 = lv_label_create(ui_Container14);
lv_obj_set_width( ui_batteryPercent3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_batteryPercent3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_batteryPercent3, 132 );
lv_obj_set_y( ui_batteryPercent3, 63 );
lv_obj_set_align( ui_batteryPercent3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_batteryPercent3,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_batteryPercent3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_batteryPercent3,"75%");
ui_object_set_themeable_style_property(ui_batteryPercent3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_white);
ui_object_set_themeable_style_property(ui_batteryPercent3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_white);
lv_obj_set_style_text_font(ui_batteryPercent3, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_pageChangeButton, ui_event_pageChangeButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_timer_arc, ui_event_timer_arc, LV_EVENT_VALUE_CHANGED, NULL);
uic_Arc3 = ui_textBackground;

// Create current time label - positioned in middle of screen for visibility during testing
ui_currentTimeLabel = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_currentTimeLabel, LV_SIZE_CONTENT);
lv_obj_set_height( ui_currentTimeLabel, LV_SIZE_CONTENT);
lv_obj_set_x( ui_currentTimeLabel, 0 );
lv_obj_set_y( ui_currentTimeLabel, 180 );
lv_obj_set_align( ui_currentTimeLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_currentTimeLabel, "00:00:00");
lv_obj_set_style_text_color(ui_currentTimeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_currentTimeLabel, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

}

// Update Screen 1 with countdown to current event end OR next event start
void ui_Screen1_updateCountdown(void)
{
    if (!ui_timeLabel || !ui_eventLabel) {
        return;  // Labels not initialized
    }

    // Get current and next events
    ScheduleEvent* currentEvent = getCurrentScheduleEvent();
    ScheduleEvent* nextEvent = getNextScheduleEvent();
    uint16_t currentMinutes = getCurrentMinutesSinceMidnight();
    
    // Get current time with seconds for accurate countdown
    time_t now = time(NULL);
    struct tm* timeinfo = localtime(&now);
    uint32_t currentSeconds = currentMinutes * 60 + timeinfo->tm_sec;
    
    if (currentEvent) {
        // Current event is active - countdown to when it ENDS
        uint16_t minutesRemaining = getMinutesRemainingInCurrentEvent();
        uint32_t eventEndSeconds = (currentEvent->start + (currentEvent->duration / 60)) * 60;
        uint32_t secondsRemaining = eventEndSeconds - currentSeconds;
        
        if (secondsRemaining < 0) secondsRemaining = 0;
        
        // Convert to hours, minutes, seconds
        uint16_t hours = secondsRemaining / 3600;
        uint16_t mins = (secondsRemaining % 3600) / 60;
        uint16_t secs = secondsRemaining % 60;
        
        // Format countdown display
        char countdownStr[16];
        if (hours > 0) {
            // HH:MM:SS format for >= 1 hour
            snprintf(countdownStr, sizeof(countdownStr), "%u:%02u:%02u", hours, mins, secs);
        } else {
            // MM:SS format for < 1 hour
            snprintf(countdownStr, sizeof(countdownStr), "%u:%02u", mins, secs);
        }
        
        // Update labels directly AND via display_state to prevent overwriting
        lv_label_set_text(ui_timeLabel, countdownStr);
        lv_label_set_text(ui_eventLabel, currentEvent->label);
        update_event_text(currentEvent->label);
        update_time_text(countdownStr);
        
        printf("[SCREEN1] Current event: %s ends in %s\\n", currentEvent->label, countdownStr);
    } else if (nextEvent) {
        // No current event - hide labels but keep arc animating silently
        lv_label_set_text(ui_eventLabel, "");
        lv_label_set_text(ui_timeLabel, "");
        update_event_text("");
        update_time_text("");
        
        printf("[SCREEN1] No current event, waiting for next event\\n");
    } else {
        // No events today - show blank labels
        lv_label_set_text(ui_eventLabel, "");
        lv_label_set_text(ui_timeLabel, "");
        update_event_text("");
        update_time_text("");
        printf("[SCREEN1] No events today\\n");
    }
}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Image1= NULL;
uic_Arc3= NULL;
ui_textBackground= NULL;
ui_eventOverlay= NULL;
ui_timer_arc= NULL;
ui_Image5= NULL;
ui_pageChangeButton= NULL;
ui_Container5= NULL;
ui_timeLabel= NULL;
ui_eventLabel= NULL;
ui_currentTimeLabel= NULL;
ui_Container14= NULL;
ui_batteryBar3= NULL;
ui_batteryPercent3= NULL;

}
