// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Screen3 = NULL;
lv_obj_t *ui_Bar1 = NULL;
lv_obj_t *ui_Arc2 = NULL;
lv_obj_t *ui_Panel6 = NULL;
lv_obj_t *ui_Label20 = NULL;
lv_obj_t *ui_Button5 = NULL;
lv_obj_t *ui_Container17 = NULL;
lv_obj_t *ui_Container12 = NULL;
lv_obj_t *ui_Container10 = NULL;
lv_obj_t *ui_Label16 = NULL;
lv_obj_t *ui_Label22 = NULL;
lv_obj_t *ui_Container11 = NULL;
lv_obj_t *ui_Slider1 = NULL;
lv_obj_t *ui_Switch1 = NULL;
lv_obj_t *ui_Container13 = NULL;
lv_obj_t *ui_batteryBar2 = NULL;
lv_obj_t *ui_batteryPercent2 = NULL;

// event funtions
void ui_event_Button5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_Screen2, LV_SCR_LOAD_ANIM_FADE_OUT, 100, 0, &ui_Screen2_screen_init);
}
}

// build funtions

void ui_Screen3_screen_init(void)
{
ui_Screen3 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Bar1 = lv_bar_create(ui_Screen3);
lv_bar_set_value(ui_Bar1,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_Bar1, 75, LV_ANIM_OFF);
lv_obj_set_width( ui_Bar1, 50);
lv_obj_set_height( ui_Bar1, 10);
lv_obj_set_x( ui_Bar1, -989 );
lv_obj_set_y( ui_Bar1, -191 );
lv_obj_set_align( ui_Bar1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Bar1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags


//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_Bar1,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_Bar1, lv_obj_get_style_pad_right(ui_Bar1,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_Arc2 = lv_arc_create(ui_Screen3);
lv_obj_set_width( ui_Arc2, 480);
lv_obj_set_height( ui_Arc2, 480);
lv_obj_set_align( ui_Arc2, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Arc2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_arc_set_value(ui_Arc2, 50);
lv_arc_set_bg_angles(ui_Arc2,0,360);
ui_object_set_themeable_style_property(ui_Arc2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR, _ui_theme_color_Navy_Blue);
ui_object_set_themeable_style_property(ui_Arc2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_ARC_OPA, _ui_theme_alpha_Navy_Blue);

lv_obj_set_style_arc_width(ui_Arc2, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Arc2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Arc2, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

    /// Flags

ui_Label20 = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_Label20, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label20, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label20, -190 );
lv_obj_set_y( ui_Label20, 0 );
lv_obj_set_align( ui_Label20, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label20,"<");
lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button5 = lv_button_create(ui_Screen3);
lv_obj_set_width( ui_Button5, 80);
lv_obj_set_height( ui_Button5, 80);
lv_obj_set_x( ui_Button5, -200 );
lv_obj_set_y( ui_Button5, 0 );
lv_obj_set_align( ui_Button5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Button5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Button5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container17 = lv_obj_create(ui_Screen3);
lv_obj_remove_style_all(ui_Container17);
lv_obj_set_width( ui_Container17, 300);
lv_obj_set_height( ui_Container17, 295);
lv_obj_set_x( ui_Container17, 1 );
lv_obj_set_y( ui_Container17, -22 );
lv_obj_set_align( ui_Container17, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Container17, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_scrollbar_mode(ui_Container17, LV_SCROLLBAR_MODE_OFF);
lv_obj_remove_flag(ui_Container17, LV_OBJ_FLAG_SCROLLABLE); 
lv_obj_set_style_bg_color(ui_Container17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Container17, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Container17, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Container17, 150, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Container12 = lv_obj_create(ui_Container17);
lv_obj_remove_style_all(ui_Container12);
lv_obj_set_width( ui_Container12, 305);
lv_obj_set_height( ui_Container12, 316);
lv_obj_set_x( ui_Container12, -3 );
lv_obj_set_y( ui_Container12, -9 );
lv_obj_set_align( ui_Container12, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container12,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container12, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Container12, LV_OBJ_FLAG_CLICKABLE );    /// Flags

ui_Container10 = lv_obj_create(ui_Container12);
lv_obj_remove_style_all(ui_Container10);
lv_obj_set_width( ui_Container10, 117);
lv_obj_set_height( ui_Container10, 186);
lv_obj_set_x( ui_Container10, 63 );
lv_obj_set_y( ui_Container10, 241 );
lv_obj_set_align( ui_Container10, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container10,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container10, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Container10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Container10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label16 = lv_label_create(ui_Container10);
lv_obj_set_width( ui_Label16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label16, -290 );
lv_obj_set_y( ui_Label16, 17 );
lv_obj_set_align( ui_Label16, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label16,"Screen\nBrightness");
ui_object_set_themeable_style_property(ui_Label16, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_white);
ui_object_set_themeable_style_property(ui_Label16, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_white);
lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label22 = lv_label_create(ui_Container10);
lv_obj_set_width( ui_Label22, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label22, LV_SIZE_CONTENT);   /// -5
lv_obj_set_x( ui_Label22, -152 );
lv_obj_set_y( ui_Label22, -6 );
lv_obj_set_align( ui_Label22, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label22,"Alarm");
ui_object_set_themeable_style_property(ui_Label22, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_white);
ui_object_set_themeable_style_property(ui_Label22, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_white);
lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container11 = lv_obj_create(ui_Container12);
lv_obj_remove_style_all(ui_Container11);
lv_obj_set_width( ui_Container11, 203);
lv_obj_set_height( ui_Container11, 196);
lv_obj_set_x( ui_Container11, 1003 );
lv_obj_set_y( ui_Container11, -109 );
lv_obj_set_align( ui_Container11, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container11,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container11, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Container11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Container11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Slider1 = lv_slider_create(ui_Container11);
lv_slider_set_value( ui_Slider1, 45, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_Slider1)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_Slider1, 65, LV_ANIM_OFF);
lv_obj_set_width( ui_Slider1, 161);
lv_obj_set_height( ui_Slider1, 10);
lv_obj_set_x( ui_Slider1, -4 );
lv_obj_set_y( ui_Slider1, -9 );
lv_obj_set_align( ui_Slider1, LV_ALIGN_CENTER );
ui_object_set_themeable_style_property(ui_Slider1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Baby_Blue);
ui_object_set_themeable_style_property(ui_Slider1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Baby_Blue);

ui_object_set_themeable_style_property(ui_Slider1, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Navy_Blue);
ui_object_set_themeable_style_property(ui_Slider1, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Navy_Blue);

ui_object_set_themeable_style_property(ui_Slider1, LV_PART_KNOB| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Navy_Blue);
ui_object_set_themeable_style_property(ui_Slider1, LV_PART_KNOB| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Navy_Blue);

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_Slider1,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_Slider1, lv_obj_get_style_pad_right(ui_Slider1,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_Switch1 = lv_switch_create(ui_Container11);
lv_obj_set_width( ui_Switch1, 50);
lv_obj_set_height( ui_Switch1, 25);
lv_obj_set_align( ui_Switch1, LV_ALIGN_CENTER );
lv_obj_add_state( ui_Switch1, LV_STATE_CHECKED );     /// States
ui_object_set_themeable_style_property(ui_Switch1, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BG_COLOR, _ui_theme_color_Navy_Blue);
ui_object_set_themeable_style_property(ui_Switch1, LV_PART_MAIN| LV_STATE_CHECKED, LV_STYLE_BG_OPA, _ui_theme_alpha_Navy_Blue);

ui_object_set_themeable_style_property(ui_Switch1, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_white);
ui_object_set_themeable_style_property(ui_Switch1, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_white);
ui_object_set_themeable_style_property(ui_Switch1, LV_PART_INDICATOR| LV_STATE_CHECKED, LV_STYLE_BG_COLOR, _ui_theme_color_Baby_Blue);
ui_object_set_themeable_style_property(ui_Switch1, LV_PART_INDICATOR| LV_STATE_CHECKED, LV_STYLE_BG_OPA, _ui_theme_alpha_Baby_Blue);

ui_object_set_themeable_style_property(ui_Switch1, LV_PART_KNOB| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Navy_Blue);
ui_object_set_themeable_style_property(ui_Switch1, LV_PART_KNOB| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Navy_Blue);
ui_object_set_themeable_style_property(ui_Switch1, LV_PART_KNOB| LV_STATE_CHECKED, LV_STYLE_BG_COLOR, _ui_theme_color_Navy_Blue);
ui_object_set_themeable_style_property(ui_Switch1, LV_PART_KNOB| LV_STATE_CHECKED, LV_STYLE_BG_OPA, _ui_theme_alpha_Navy_Blue);

ui_Container13 = lv_obj_create(ui_Screen3);
lv_obj_remove_style_all(ui_Container13);
lv_obj_set_width( ui_Container13, 104);
lv_obj_set_height( ui_Container13, 45);
lv_obj_set_x( ui_Container13, 0 );
lv_obj_set_y( ui_Container13, -200 );
lv_obj_set_align( ui_Container13, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container13,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container13, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_batteryBar2 = lv_bar_create(ui_Container13);
lv_bar_set_value(ui_batteryBar2,75,LV_ANIM_OFF);
lv_bar_set_start_value(ui_batteryBar2, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_batteryBar2, 50);
lv_obj_set_height( ui_batteryBar2, 20);
lv_obj_set_x( ui_batteryBar2, 78 );
lv_obj_set_y( ui_batteryBar2, 63 );
lv_obj_set_align( ui_batteryBar2, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_batteryBar2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_batteryBar2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_batteryBar2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_batteryBar2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_batteryBar2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_batteryBar2, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_batteryBar2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_batteryBar2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_batteryBar2, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_batteryBar2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_batteryBar2,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_batteryBar2, lv_obj_get_style_pad_right(ui_batteryBar2,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_batteryPercent2 = lv_label_create(ui_Container13);
lv_obj_set_width( ui_batteryPercent2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_batteryPercent2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_batteryPercent2, 132 );
lv_obj_set_y( ui_batteryPercent2, 63 );
lv_obj_set_align( ui_batteryPercent2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_batteryPercent2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_batteryPercent2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_batteryPercent2,"75%");
ui_object_set_themeable_style_property(ui_batteryPercent2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_white);
ui_object_set_themeable_style_property(ui_batteryPercent2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_white);
lv_obj_set_style_text_font(ui_batteryPercent2, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
   if (ui_Screen3) lv_obj_del(ui_Screen3);

// NULL screen variables
ui_Screen3= NULL;
ui_Bar1= NULL;
ui_Arc2= NULL;
ui_Panel6= NULL;
ui_Label20= NULL;
ui_Button5= NULL;
ui_Container17= NULL;
ui_Container12= NULL;
ui_Container10= NULL;
ui_Label16= NULL;
ui_Label22= NULL;
ui_Container11= NULL;
ui_Slider1= NULL;
ui_Switch1= NULL;
ui_Container13= NULL;
ui_batteryBar2= NULL;
ui_batteryPercent2= NULL;

}
