// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_NAVY_BLUE 0
#define UI_THEME_COLOR_BABY_BLUE 1
#define UI_THEME_COLOR_BLACK 2
#define UI_THEME_COLOR_BABY_YELLOW 3
#define UI_THEME_COLOR_WHITE 4

#define UI_THEME_DEFAULT 0

extern const ui_theme_variable_t _ui_theme_color_Navy_Blue[1];
extern const ui_theme_variable_t _ui_theme_alpha_Navy_Blue[1];

extern const ui_theme_variable_t _ui_theme_color_Baby_Blue[1];
extern const ui_theme_variable_t _ui_theme_alpha_Baby_Blue[1];

extern const ui_theme_variable_t _ui_theme_color_black[1];
extern const ui_theme_variable_t _ui_theme_alpha_black[1];

extern const ui_theme_variable_t _ui_theme_color_baby_yellow[1];
extern const ui_theme_variable_t _ui_theme_alpha_baby_yellow[1];

extern const ui_theme_variable_t _ui_theme_color_white[1];
extern const ui_theme_variable_t _ui_theme_alpha_white[1];

extern const uint32_t* ui_theme_colors[1];
extern const uint8_t* ui_theme_alphas[1];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
